server:
  port: 9100

spring:
  application:
    name: noun-service
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.51:8761/eureka/
