server:
  port: 8761

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: eureka
  cloud:
    config:
      discovery:
        enabled: true
